package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

const (
	installDir        = "/opt/probakgo"
	logDir            = "/var/log/probakgo"
	logrotateConfPath = "/etc/logrotate.d/probakgo"
	clientCronPath    = "/etc/cron.d/probakgo-client"
	vzdumpConfPath    = "/etc/vzdump.conf"
	hookPath          = installDir + "/vzdump_client.sh"
	envPath           = installDir + "/.env"
	binaryPath        = installDir + "/probakgo-client"
)

// Generated and written to hookPath during install - no separate shell script needed.
const hookScript = `#!/bin/bash
# Generated by: probakgo-client install
INSTALL_DIR="/opt/probakgo"
LOG_DIR="/var/log/probakgo"
LOCK_FILE="$INSTALL_DIR/.probakgo.lock"
LOG_FILE="$LOG_DIR/hook.log"
PENDING_FILE="$INSTALL_DIR/.report_pending"

log_msg() { echo "$(date '+%Y-%m-%d %H:%M:%S') $1" >> "$LOG_FILE"; }

if [ "$1" = "job-end" ]; then
    log_msg "INFO: Backup completed, reporting..."
    touch "$LOCK_FILE"; chmod 666 "$LOCK_FILE"
    (
        flock -w 30 200 || {
            log_msg "WARN: Could not acquire lock, saving as pending"
            echo "$(date '+%Y-%m-%d %H:%M:%S')" > "$PENDING_FILE"
            exit 0
        }
        log_msg "INFO: Running probakgo-client..."
        "$INSTALL_DIR/probakgo-client" --vzdump-hook >> "$LOG_FILE" 2>&1
        log_msg "INFO: Exit code: $?"
        [ -f "$PENDING_FILE" ] && rm -f "$PENDING_FILE"
    ) 200>"$LOCK_FILE"
fi
exit 0
`

const logrotateConf = `/var/log/probakgo/*.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
}
`

func runInstall(args []string) {
	fs := flag.NewFlagSet("install", flag.ExitOnError)
	apiURL := fs.String("api-url", "", "probakgo server URL (e.g. http://192.168.1.10:36748)")
	apiKey := fs.String("api-key", "", "API key from probakgo web UI (must start with pbk-)")
	proxmoxToken := fs.String("proxmox-token", "", "Proxmox API token (auto-generated if omitted)")
	proxmoxSecret := fs.String("proxmox-secret", "", "Proxmox API token secret (auto-generated if omitted)")
	githubToken := fs.String("github-token", "", "GitHub token for self-update (required for private repos)")
	replaceEnv := fs.Bool("replace-env", false, "Overwrite existing .env (default: preserve on reinstall)")
	fs.Usage = func() {
		fmt.Println("Usage: probakgo-client install [flags]")
		fmt.Println("\nInstalls probakgo-client on this Proxmox node and configures the vzdump hook.")
		fmt.Println("\nFlags:")
		fs.PrintDefaults()
		fmt.Println("\nExample:")
		fmt.Println("  probakgo-client install --api-url http://10.0.0.1:36748 --api-key pbk-...")
	}
	_ = fs.Parse(args)

	if os.Getuid() != 0 {
		fatalf("install must be run as root (sudo or su -)")
	}

	// 1. Create directories
	must(os.MkdirAll(installDir, 0755), "create install dir")
	must(os.MkdirAll(logDir, 0755), "create log dir")
	fmt.Printf("Directories ready: %s, %s\n", installDir, logDir)

	// 2. Copy self to install location
	self, err := os.Executable()
	must(err, "locate executable")
	self, err = filepath.EvalSymlinks(self)
	must(err, "resolve symlinks")
	selfAbs, _ := filepath.Abs(self)

	if selfAbs != binaryPath {
		must(copyExec(self, binaryPath), "copy binary")
		fmt.Printf("Binary installed: %s\n", binaryPath)
	} else {
		fmt.Println("Binary already at install location")
	}

	// 3. .env: generate Proxmox token if not provided, then write
	preserveEnv := !*replaceEnv
	if _, err := os.Stat(envPath); err == nil && preserveEnv {
		fmt.Println(".env already exists - preserving (use --replace-env to overwrite)")
	} else {
		if *proxmoxToken == "" || *proxmoxSecret == "" {
			tok, sec, err := generateProxmoxToken("probakgo-client")
			if err != nil {
				fmt.Printf("WARN: %v\n", err)
				fmt.Println("      Set PROXMOX_TOKEN and PROXMOX_SECRET manually in " + envPath)
			} else {
				*proxmoxToken = tok
				*proxmoxSecret = sec
			}
		}
		must(writeEnv(*apiKey, *apiURL, *proxmoxToken, *proxmoxSecret, *githubToken), "write .env")
		fmt.Printf(".env written: %s\n", envPath)
		if *apiKey == "" {
			fmt.Println("WARN: API key not set - edit " + envPath + " and add API_KEY=pbk-...")
		}
	}

	// 4. Write vzdump hook script
	must(os.WriteFile(hookPath, []byte(hookScript), 0755), "write hook script")
	fmt.Printf("Hook script: %s\n", hookPath)

	// 5. Register hook in /etc/vzdump.conf (PVE) or cron report (PBS)
	isPBS := false
	if _, err := os.Stat(vzdumpConfPath); err == nil {
		hookLine := "script: " + hookPath
		if !fileContains(vzdumpConfPath, hookLine) {
			f, err := os.OpenFile(vzdumpConfPath, os.O_APPEND|os.O_WRONLY, 0644)
			must(err, "open vzdump.conf")
			_, err = fmt.Fprintf(f, "%s\n", hookLine)
			f.Close()
			must(err, "write vzdump.conf")
			fmt.Println("Hook registered in /etc/vzdump.conf")
		} else {
			fmt.Println("Hook already in /etc/vzdump.conf")
		}
	} else {
		isPBS = true
		fmt.Println("PBS node: report cron will be installed (no vzdump hook needed)")
	}

	// 6. Configure logrotate
	must(os.WriteFile(logrotateConfPath, []byte(logrotateConf), 0644), "write logrotate config")
	fmt.Println("logrotate: " + logrotateConfPath)

	// 7. Install cron: auto-update at 01:00 + PBS daily report at 06:00
	cronContent := fmt.Sprintf("0 1 * * * root %s update >> %s/update.log 2>&1\n", binaryPath, logDir)
	if isPBS {
		cronContent += fmt.Sprintf("0 6 * * * root %s >> %s/report.log 2>&1\n", binaryPath, logDir)
	}
	if err := os.WriteFile(clientCronPath, []byte(cronContent), 0644); err != nil {
		fmt.Printf("WARN: could not install cron: %v\n", err)
	} else {
		if isPBS {
			fmt.Printf("Cron installed: %s (update 01:00, report 06:00)\n", clientCronPath)
		} else {
			fmt.Printf("Auto-update cron installed: %s\n", clientCronPath)
		}
	}

	fmt.Println("\nInstallation complete!")
	if *apiKey == "" {
		fmt.Printf("  Next: edit %s\n", envPath)
	}
	fmt.Printf("  Test:   %s\n", binaryPath)
	fmt.Printf("  Update: %s update\n", binaryPath)
}

func runUninstall(_ []string) {
	if os.Getuid() != 0 {
		fatalf("uninstall must be run as root (sudo or su -)")
	}

	// 1. Remove hook line from /etc/vzdump.conf
	if data, err := os.ReadFile(vzdumpConfPath); err == nil {
		hookLine := "script: " + hookPath
		var kept []string
		for _, line := range strings.Split(string(data), "\n") {
			if strings.TrimSpace(line) != hookLine {
				kept = append(kept, line)
			}
		}
		updated := strings.Join(kept, "\n")
		if updated != string(data) {
			if err := os.WriteFile(vzdumpConfPath, []byte(updated), 0644); err != nil {
				fmt.Printf("WARN: could not update %s: %v\n", vzdumpConfPath, err)
			} else {
				fmt.Printf("Hook removed from %s\n", vzdumpConfPath)
			}
		}
	}

	// 2. Revoke Proxmox API token
	tokenID := "probakgo-client"
	if _, err := exec.LookPath("pveum"); err == nil {
		if err := exec.Command("pveum", "user", "token", "remove", "root@pam", tokenID).Run(); err != nil {
			fmt.Printf("WARN: could not remove PVE token: %v\n", err)
		} else {
			fmt.Println("PVE API token revoked")
		}
	} else if _, err := exec.LookPath("proxmox-backup-manager"); err == nil {
		if err := exec.Command("proxmox-backup-manager", "user", "delete-token", "root@pam", tokenID).Run(); err != nil {
			fmt.Printf("WARN: could not remove PBS token: %v\n", err)
		} else {
			fmt.Println("PBS API token revoked")
		}
	}

	// 3. Remove installed files and directories
	for _, path := range []string{clientCronPath, logrotateConfPath} {
		if err := os.Remove(path); err == nil {
			fmt.Printf("Removed: %s\n", path)
		}
	}
	for _, dir := range []string{installDir, logDir} {
		if err := os.RemoveAll(dir); err == nil {
			fmt.Printf("Removed: %s\n", dir)
		}
	}

	fmt.Println("\nUninstall complete.")
}

func generateProxmoxToken(tokenID string) (token, secret string, err error) {
	if _, e := exec.LookPath("pveum"); e == nil {
		fmt.Println("Generating Proxmox VE API token...")
		_ = exec.Command("pveum", "user", "token", "remove", "root@pam", tokenID).Run()
		out, e := exec.Command("pveum", "user", "token", "add", "root@pam", tokenID,
			"--privsep", "0", "--comment", "probakgo monitoring client", "--output-format", "json").Output()
		if e == nil {
			if val := jsonField(out, "value"); val != "" {
				fmt.Println("PVE API token generated")
				return "root@pam!" + tokenID, val, nil
			}
		}
		fmt.Printf("WARN: pveum token creation failed: %v\n", e)
	}

	if _, e := exec.LookPath("proxmox-backup-manager"); e == nil {
		fmt.Println("Generating Proxmox Backup Server API token...")
		_ = exec.Command("proxmox-backup-manager", "user", "delete-token", "root@pam", tokenID).Run()
		if val := runPBSGenerateToken(tokenID); val != "" {
			fmt.Println("PBS API token generated")
			grantPBSTokenACL(tokenID)
			return "root@pam!" + tokenID, val, nil
		}
		return "", "", fmt.Errorf("proxmox-backup-manager token creation failed; set PROXMOX_TOKEN and PROXMOX_SECRET manually in %s", envPath)
	}

	return "", "", fmt.Errorf("pveum and proxmox-backup-manager not found; configure credentials manually")
}

// grantPBSTokenACL grants the Audit role on / so the token can read datastore-usage.
func grantPBSTokenACL(tokenID string) {
	authID := "root@pam!" + tokenID
	err := exec.Command("proxmox-backup-manager", "acl", "update", "/", "Audit",
		"--auth-id", authID).Run()
	if err != nil {
		fmt.Printf("WARN: could not set ACL for %s: %v\n", authID, err)
		fmt.Printf("      Run manually: proxmox-backup-manager acl update / Audit --auth-id '%s'\n", authID)
	} else {
		fmt.Printf("ACL granted: %s → Audit on /\n", authID)
	}
}

// runPBSGenerateToken tries several invocation styles for proxmox-backup-manager
// and returns the token secret on success, or "" on failure.
func runPBSGenerateToken(tokenID string) string {
	// Try: flag after subcommand args, then flag before subcommand (some PBS versions differ)
	attempts := [][]string{
		{"user", "generate-token", "root@pam", tokenID, "--output-format", "json"},
		{"--output-format", "json", "user", "generate-token", "root@pam", tokenID},
		{"user", "generate-token", "root@pam", tokenID},
	}
	for _, args := range attempts {
		cmd := exec.Command("proxmox-backup-manager", args...)
		out, e := cmd.Output()
		if e != nil {
			var exitErr *exec.ExitError
			if errors.As(e, &exitErr) && len(exitErr.Stderr) > 0 {
				fmt.Printf("WARN: generate-token: %s\n", strings.TrimSpace(string(exitErr.Stderr)))
			}
			continue
		}
		if val := jsonField(out, "value"); val != "" {
			return val
		}
		if val := extractUUID(string(out)); val != "" {
			return val
		}
	}
	return ""
}

var uuidRe = regexp.MustCompile(`[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`)

func extractUUID(s string) string {
	return uuidRe.FindString(s)
}

func jsonField(data []byte, key string) string {
	var m map[string]any
	if json.Unmarshal(data, &m) != nil {
		return ""
	}
	v, _ := m[key].(string)
	return v
}

func writeEnv(apiKey, apiURL, proxmoxToken, proxmoxSecret, githubToken string) error {
	if apiURL == "" {
		apiURL = "http://localhost:36748"
	}
	ghLine := "# GITHUB_TOKEN=ghp_..."
	if githubToken != "" {
		ghLine = "GITHUB_TOKEN=" + githubToken
	}
	content := fmt.Sprintf(`# probakgo client configuration
API_KEY=%s
API_URL=%s
PROXMOX_TOKEN=%s
PROXMOX_SECRET=%s
# Set to false for self-signed certificates (Proxmox default)
PROXMOX_VERIFY_TLS=false
# GitHub token for self-update (required if repo is private)
%s
`, apiKey, apiURL, proxmoxToken, proxmoxSecret, ghLine)
	return os.WriteFile(envPath, []byte(content), 0600)
}

func copyExec(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.OpenFile(dst, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}

func fileContains(path, substr string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), substr)
}

func must(err error, msg string) {
	if err != nil {
		fatalf("%s: %v", msg, err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "ERROR: "+format+"\n", args...)
	os.Exit(1)
}
