ALTER TABLE pve_reports ADD COLUMN swap_total INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pve_reports ADD COLUMN swap_used INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pve_reports ADD COLUMN swap_enabled INTEGER NOT NULL DEFAULT 0;

ALTER TABLE pbs_reports ADD COLUMN swap_total INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pbs_reports ADD COLUMN swap_used INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pbs_reports ADD COLUMN swap_enabled INTEGER NOT NULL DEFAULT 0;
